version: 2

models:
  # Bronze Layer
  - name: stg_bids
    description: "Staging model for bid/procurement data"
    columns:
      - name: sequence_no
        description: "Unique sequence number for each bid"
        tests:
          - unique
          - not_null

  # Silver Layer
  - name: int_orders_enriched
    description: "Orders enriched with corporate information"
    columns:
      - name: sequence_no
        tests:
          - unique
          - not_null
      - name: organization_name
        tests:
          - not_null

  # Gold Layer
  - name: gold_ledger
    description: "Main order ledger with billing status"
    columns:
      - name: sequence_no
        tests:
          - unique
          - not_null
      - name: billing_status
        tests:
          - not_null
          - accepted_values:
              values: ['UNBILLED', 'BILLED', 'PAID', 'OVERDUE', 'INVALID']

  - name: gold_invoices
    description: "Invoice records for orders"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: invoice_number
        tests:
          - unique
          - not_null
      - name: invoice_amount
        tests:
          - not_null

  - name: gold_payments
    description: "Payment records for invoices"
    columns:
      - name: invoice_number
        tests:
          - not_null
      - name: payment_status
        tests:
          - not_null
          - accepted_values:
              values: ['PAID', 'PAID_LATE', 'UNPAID']

  - name: gold_exceptions
    description: "Exception detection for billing/payment issues"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: exception_type
        tests:
          - not_null
          - accepted_values:
              values: ['UNBILLED', 'OVERDUE', 'AMOUNT_MISMATCH']
      - name: severity
        tests:
          - not_null
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']

  - name: gold_documents
    description: "Searchable document index"
    columns:
      - name: doc_id
        tests:
          - unique
          - not_null
      - name: content
        description: "Full text content"

