version: 2

sources:
  - name: raw_data
    schema: main
    tables:
      - name: bids
        meta:
          external_location: "data/raw/bids_raw.parquet"
      - name: corporate
        meta:
            external_location: "data/raw/corporate_raw.parquet"
      - name: documents
        meta:
            external_location: "data/raw/documents_raw.parquet"
